// data.js - Auto-generated from plain-tho.txt

const QUESTIONS_DATA = [
    "Giơ một ngón tay xuống nếu bạn đã từng vi phạm lỗi trong ba năm cấp 3", // 1
    "Giơ một ngón tay xuống nếu bạn đã từng thấy mình không hợp với lớp này", // 3
    "Giơ một ngón tay xuống nếu bạn hãy bỏ một ngón tay xuống nếu bạn từng cãi nhau nảy lửa với các thành viên khác khi làm bài tập hay dự án nhóm.", // 5
    "Giơ một ngón tay xuống nếu bạn thấy ngưỡng mộ một người bạn cùng lớp.", // 13
    "Giơ một ngón tay xuống nếu bạn đã từng rơi nước mắt vì một bài kiểm tra, hay một kì thi nào đó", // 2
    "Giơ một ngón tay xuống nếu bạn đã có 1 nuối tiếc hay ân hận về 1 việc gì đó trong năm cấp 3 và muốn quay thời gian để sửa nó", // 15
    "Giơ một ngón tay xuống nếu bạn cảm thấy mình muốn nói lời cảm ơn đến người bạn cùng bàn", // 14
    "Giơ một ngón tay xuống nếu bạn thấy trong lớp mình có một người khiến bạn rất thoải mái, an tâm khi ở gần", // 8
    "Giơ một ngón tay xuống nếu bạn thấy thứ quý giá nhất bạn nhận được sau 3 năm không phải là kiến thức mà là những món quan hệ bạn bè và thầy cô chất lượng", // 9
    "Giơ một ngón tay xuống nếu bạn thấy mình rất là biết ơn khi có những người ban cán sự lớp tuyệt vời như vậy", // 4
    "Giơ một ngón tay xuống nếu bạn thấy mình muốn cảm ơn các thầy cô trong trường, đặc biệt là thầy trọn", // 7
    "Giơ một ngón tay xuống nếu bạn hãy bỏ một ngón tay xuống nếu nhìn lại, bạn thấy bản thân đã \"lột xác\" thành một con người trưởng thành hơn rất nhiều so với ngày đầu nhập học", // 6
    "Giơ một ngón tay xuống nếu bạn thấy tự hào về bản thân mình vì đã cố gắng hết sức mình.", // 12
    "Giơ một ngón tay xuống nếu bạn vẫn sẽ chọn t1k23 nếu được quay trở lại ngày thi ts10", // 10
    "Giơ một ngón tay xuống nếu bạn mong cho các đối thủ của mình sẽ đậu nv1 và thành công trên con đường sau này." // 11
];

const CLASS_DATA = [
    {
        id: 1,
        name: "Thầy Trọn",
        title: "Người ba, Người thầy, Người bạn",
        fact: "Ai là Người ba, Người thầy, Người bạn của 12T1?",
        birthday: "1",
        voucher: "HEAKY#50662026",
        mainImg: "assets/members/Anh Trọn/IMG_1722.JPG",
        subImgs: ["assets/members/Anh Trọn/IMG_4123.JPG", "assets/members/Anh Trọn/IMG_4124.JPG", "assets/members/Anh Trọn/IMG_4125.JPG", "assets/members/Anh Trọn/IMG_4126.JPG", "assets/members/Anh Trọn/IMG_4127.JPG", "assets/members/Anh Trọn/IMG_4128.JPG", "assets/members/Anh Trọn/IMG_4129.JPG", "assets/members/Anh Trọn/IMG_4130.JPG", "assets/members/Anh Trọn/IMG_4131.JPG", "assets/members/Anh Trọn/IMG_4132.JPG", "assets/members/Anh Trọn/IMG_4133.JPG", "assets/members/Anh Trọn/IMG_4134.JPG"]
    },
    {
        id: 2,
        name: "Võ Nguyễn Hoàng Long",
        title: "Đa năng hơn cả AI",
        fact: "Ai là người đa năng hơn cả AI?",
        birthday: "06/06",
        voucher: "HEAKY#36672026",
        mainImg: "assets/members/Hoàng Long/main image.jpg",
        subImgs: ["assets/members/Hoàng Long/10.jpg", "assets/members/Hoàng Long/11.jpg", "assets/members/Hoàng Long/7.jpg", "assets/members/Hoàng Long/9.jpg"]
    },
    {
        id: 3,
        name: "Trương Minh Khoa",
        title: "Biết tuốt",
        fact: "Ai là người biết tuốt - hỏi cái gì cũng biết hết trơn?",
        birthday: "08/10",
        voucher: "HEAKY#80142026",
        mainImg: "assets/members/Minh Khoa/main.jpg",
        subImgs: ["assets/members/Minh Khoa/1.jpg", "assets/members/Minh Khoa/3.jpg", "assets/members/Minh Khoa/4.jpg", "assets/members/Minh Khoa/5.jpg"]
    },
    {
        id: 4,
        name: "Nguyễn Đức Nhuận Phát",
        title: "Con người nhiều cảm xúc",
        fact: "Ai là con người nhiều cảm xúc?",
        birthday: "01/07",
        voucher: "HEAKY#20622026",
        mainImg: "assets/members/Nhuận Phát/IMG_0580.JPG",
        subImgs: ["assets/members/Nhuận Phát/IMG_2415.JPG", "assets/members/Nhuận Phát/IMG_3935.JPG", "assets/members/Nhuận Phát/IMG_7885.jpeg", "assets/members/Nhuận Phát/IMG_9400.JPG"]
    },
    {
        id: 5,
        name: "Phạm Liêu Hoàng Triều",
        title: "Đỉnh kout của sự trả thù",
        fact: "Ai là đỉnh kout của sự trả thù?",
        birthday: "24/02",
        voucher: "HEAKY#90742026",
        mainImg: "assets/members/Triều/DSCF9902.JPG",
        subImgs: ["assets/members/Triều/IMG_1972.JPG", "assets/members/Triều/IMG_2223.JPG", "assets/members/Triều/IMG_2260.JPG", "assets/members/Triều/IMG_2307.JPG", "assets/members/Triều/IMG_5177.JPG", "assets/members/Triều/IMG_5201.JPG", "assets/members/Triều/IMG_9781.JPG"]
    },
    {
        id: 6,
        name: "Phan Lê Ánh Ngọc",
        title: "Nụ cười đầy năng lượng",
        fact: "Ai là người có nụ cười đầy năng lượng?",
        birthday: "29/03",
        voucher: "Cần gì thì nhắn tui tui tặng khỏi mua nha.",
        is_special: true,
        mainImg: "assets/members/Ánh Ngọc/main image.jpg",
        subImgs: ["assets/members/Ánh Ngọc/IMG_2246.JPG", "assets/members/Ánh Ngọc/IMG_2937.JPG", "assets/members/Ánh Ngọc/IMG_2938.JPG", "assets/members/Ánh Ngọc/IMG_7729.JPG", "assets/members/Ánh Ngọc/IMG_8462.JPG", "assets/members/Ánh Ngọc/IMG_9486.JPG", "assets/members/Ánh Ngọc/sub.jpg"]
    },
    {
        id: 7,
        name: "Nguyễn Quốc Gia Huy",
        title: "Người dám sống thật",
        fact: "Ai là người dám sống thật?",
        birthday: "17/01",
        voucher: "HEAKY#23222026",
        mainImg: "assets/members/Quốc Huy/Main.jpg",
        subImgs: ["assets/members/Quốc Huy/att.j_DG3H570sQxPv0DPasFBjCUVMFZSy0F4EVsT7I-WJ0.jpg", "assets/members/Quốc Huy/z7865266693088_ac430ca943783451de4f00ec8ed982bd.jpg", "assets/members/Quốc Huy/z7865291322174_261cde28d78d714356de005ae98c2e10.jpg", "assets/members/Quốc Huy/z7865313452834_4e015026719ce8826fe34bf71c24403c.jpg"]
    },
    {
        id: 8,
        name: "Lê Viết Triết",
        title: "Cọc cằn mà tử tế",
        fact: "Ai là người cọc cằn mà tử tế?",
        birthday: "24/06",
        voucher: "HEAKY#32112026",
        mainImg: "assets/members/Triết/main.jpg",
        subImgs: ["assets/members/Triết/IMG_1175.JPG", "assets/members/Triết/IMG_2262.JPG", "assets/members/Triết/IMG_3352.jpg", "assets/members/Triết/IMG_6627.JPG"]
    },
    {
        id: 9,
        name: "Mai Huỳnh Duy",
        title: "Cốt của mọi nhà",
        fact: "Ai là cốt của mọi nhà?",
        birthday: "12/12",
        voucher: "HEAKY#35082026",
        mainImg: "assets/members/Duy/main image.jpg",
        subImgs: ["assets/members/Duy/z7865100236571_6aaf42fad57d77c391607dcb7cd372ec.jpg", "assets/members/Duy/z7865100237986_5c5280f4339a1fadc1ca042ead47d38f.jpg", "assets/members/Duy/z7865100249628_d0c8d7581d1e2fd6c58048992b90e842.jpg", "assets/members/Duy/z7865100532645_4de7941e2f533b2904cf16259c567380.jpg"]
    },
    {
        id: 10,
        name: "Kiều Ngọc Thủy Tiên",
        title: "Trung tâm sự kiện",
        fact: "Ai là trung tâm sự kiện?",
        birthday: "17/11",
        voucher: "HEAKY#89602026",
        mainImg: "assets/members/Thuỷ Tiên/MAIN IMAGE CỦA TAO.jpg",
        subImgs: ["assets/members/Thuỷ Tiên/IMG_7472.JPG", "assets/members/Thuỷ Tiên/IMG_7760.JPG"]
    },
    {
        id: 11,
        name: "Phan Huỳnh Bảo Trí",
        title: "Ồn ào mà ấm áp",
        fact: "Ai là người ồn ào mà ấm áp?",
        birthday: "20/11",
        voucher: "HEAKY#39212026",
        mainImg: "assets/members/Trí/main image.JPG",
        subImgs: ["assets/members/Trí/IMG_1578.JPG", "assets/members/Trí/IMG_2985.JPG", "assets/members/Trí/IMG_3082.JPG", "assets/members/Trí/IMG_7044.JPG"]
    },
    {
        id: 12,
        name: "Nguyễn Khánh Minh",
        title: "Tổng đài 1800",
        fact: "Ai là tổng đài 1800?",
        birthday: "22/04",
        voucher: "HEAKY#21912026",
        mainImg: "assets/members/Khánh Minh/main.JPG",
        subImgs: ["assets/members/Khánh Minh/IMG_0993.JPG", "assets/members/Khánh Minh/IMG_4110.JPG", "assets/members/Khánh Minh/TIE_2820.jpeg", "assets/members/Khánh Minh/Địnhtinhs.jpg"]
    },
    {
        id: 13,
        name: "Hà Lê Bảo Nga",
        title: "Nô lệ của sự kĩ tính",
        fact: "Ai là nô lệ của sự kĩ tính?",
        birthday: "15/01",
        voucher: "HEAKY#13532026",
        mainImg: "assets/members/Bảo Nga/main image.jpg",
        subImgs: ["assets/members/Bảo Nga/10.jpg", "assets/members/Bảo Nga/IMG_20241106_101058.jpg", "assets/members/Bảo Nga/IMG_20251118_101144.jpg", "assets/members/Bảo Nga/IMG_20260214_134620.jpg", "assets/members/Bảo Nga/retouch_2026011513554244.jpg", "assets/members/Bảo Nga/retouch_2026011514303198.jpg", "assets/members/Bảo Nga/Screenshot_2026-02-14-15-19-22-083_com.locket.Locket.jpg", "assets/members/Bảo Nga/Screenshot_2026-02-14-15-21-13-023_com.locket.Locket.jpg"]
    },
    {
        id: 14,
        name: "Huỳnh Bảo Ngọc",
        title: "Cô gái hay nặng lòng",
        fact: "Ai là cô gái hay nặng lòng?",
        birthday: "31/01",
        voucher: "HEAKY#18742026",
        mainImg: "assets/members/Bảo Ngọc/main image.jpg",
        subImgs: ["assets/members/Bảo Ngọc/IMG_20260525_225325.jpg", "assets/members/Bảo Ngọc/IMG_20260525_225327.jpg", "assets/members/Bảo Ngọc/IMG_20260525_225329.jpg", "assets/members/Bảo Ngọc/IMG_20260525_225349.jpg"]
    },
    {
        id: 15,
        name: "Phạm Nguyễn Ngọc Phụng",
        title: "Cô nàng yêu mèo",
        fact: "Ai là cô nàng yêu mèo?",
        birthday: "05/04",
        voucher: "HEAKY#81272026",
        mainImg: "assets/members/Ngọc Phụng/main image_.jpg",
        subImgs: ["assets/members/Ngọc Phụng/IMG_0333.JPG", "assets/members/Ngọc Phụng/IMG_1318.JPG", "assets/members/Ngọc Phụng/IMG_7088.JPG", "assets/members/Ngọc Phụng/IMG_8738.PNG"]
    },
    {
        id: 16,
        name: "Ngô Khánh Phương",
        title: "Sai và nhiều tình",
        fact: "Ai là người sai và nhiều tình?",
        birthday: "05/01",
        voucher: "HEAKY#85042026",
        mainImg: "assets/members/kphuong/main image.png",
        subImgs: ["assets/members/kphuong/IMG_20241103_120834.jpg", "assets/members/kphuong/IMG_20260211_184103.jpg", "assets/members/kphuong/Không Có Tiêu Đề604_20260521193050.png", "assets/members/kphuong/Locket_1749890959481_22.jpg", "assets/members/kphuong/retouch_2026051121055210.jpg"]
    },
    {
        id: 17,
        name: "Bùi Gia Lộc",
        title: "Mắc cười và mắc nói",
        fact: "Ai là người hay mắc cười và mắc nói?",
        birthday: "12/7",
        voucher: "HEAKY#39122026",
        mainImg: "assets/members/Lộc/main.jpg",
        subImgs: ["assets/members/Lộc/02e5f67a8853090d5042.jpg", "assets/members/Lộc/5202be4bcf624e3c1773.jpg", "assets/members/Lộc/55c895ebe3c2629c3bd3.jpg", "assets/members/Lộc/738ad221a50824567d19.jpg", "assets/members/Lộc/aef908287701f65faf10.jpg"]
    },
    {
        id: 18,
        name: "Đặng Trường Phát",
        title: "Hài hước trong từng hành động",
        fact: "Ai là người hài hước trong từng hành động?",
        birthday: "08/09",
        voucher: "HEAKY#28772026",
        mainImg: "assets/members/Trường Phát_/F87A1903.jpg",
        subImgs: ["assets/members/Trường Phát_/F87A1907.jpg", "assets/members/Trường Phát_/IMG20210625093938.jpg", "assets/members/Trường Phát_/Messenger_creation_6A2EA4CA-5A8F-4047-9679-1D29B531BE71.jpeg", "assets/members/Trường Phát_/received_1760139654520171.jpeg"]
    },
    {
        id: 19,
        name: "Nguyễn Hoàng Phúc",
        title: "Người hay bị bully nhất 12T1",
        fact: "Ai là người hay bị bully nhất 12T1?",
        birthday: "18/11",
        voucher: "HEAKY#25922026",
        mainImg: "assets/members/Hoàng Phúc/Main.jpg",
        subImgs: ["assets/members/Hoàng Phúc/received_2411805165818431.jpeg", "assets/members/Hoàng Phúc/z7746367103890_2c288ecb482bdcfb65ad643f095f477e.jpg", "assets/members/Hoàng Phúc/z7865391733238_a73dd251a94bfc8cdc902542e1ef09fe.jpg", "assets/members/Hoàng Phúc/z7865391741589_8740a6c7d5c894b4c66ee94df13c1cf8.jpg"]
    },
    {
        id: 20,
        name: "Phạm Nhã Uyên",
        title: "Overthinking giai đoạn sắp cuối",
        fact: "Ai là người overthinking giai đoạn sắp cuối?",
        birthday: "17/08",
        voucher: "HEAKY#38162026",
        mainImg: "assets/members/Uyên nè/1.jpg",
        subImgs: ["assets/members/Uyên nè/21bfe698-3248-4b8c-8b02-c78444db8cf9.jpg", "assets/members/Uyên nè/543dc1be-3725-450d-b008-8505adb57ddc.jpg", "assets/members/Uyên nè/a16aec43-08c3-4040-bfb2-acc4a00f9f31.jpg", "assets/members/Uyên nè/d43e560d-7aba-4cdc-8b1c-d722c33bc836.jpg"]
    },
    {
        id: 21,
        name: "Nguyễn Hoàng Quốc Thắng",
        title: "Bác sĩ nhiều bệnh",
        fact: "Ai là bác sĩ nhiều bệnh?",
        birthday: "20/08",
        voucher: "HEAKY#26352026",
        mainImg: "assets/members/Thắng!/IMG_1687.JPG",
        subImgs: ["assets/members/Thắng!/IMG_1688.JPG", "assets/members/Thắng!/IMG_1689.JPG", "assets/members/Thắng!/IMG_1690.JPG", "assets/members/Thắng!/IMG_1691.JPG"]
    },
    {
        id: 22,
        name: "Đặng Trần Diễm Phúc",
        title: "Cô giáo dạy tiếng anh",
        fact: "Ai là cô giáo dạy tiếng anh?",
        birthday: "12/06",
        voucher: "HEAKY#41592026",
        mainImg: "assets/members/Diễm Phúc/main image.JPG",
        subImgs: ["assets/members/Diễm Phúc/1d90f0b344bb6b9f5b2c86db307b2eff.JPG", "assets/members/Diễm Phúc/84d6d9df1392dfa2c0b93cd604b0afa6.JPG", "assets/members/Diễm Phúc/IMG_5299.JPG", "assets/members/Diễm Phúc/IMG_5371.JPG", "assets/members/Diễm Phúc/IMG_5802.JPG"]
    },
    {
        id: 23,
        name: "Nguyễn Trọng Nhân",
        title: "Ồn ồn nhưng dễ vỡ",
        fact: "Ai là người ồn ồn nhưng dễ vỡ?",
        birthday: "11/07",
        voucher: "HEAKY#57062026",
        mainImg: "assets/members/Nhân/IMG_2109.JPG",
        subImgs: ["assets/members/Nhân/IMG_2461.JPG", "assets/members/Nhân/IMG_2463.JPG", "assets/members/Nhân/IMG_2464.JPG", "assets/members/Nhân/IMG_2465.JPG"]
    },
    {
        id: 24,
        name: "Phạm Nguyễn Thanh Ngọc",
        title: "Lặng lẽ và dịu êm",
        fact: "Ai là người lặng lẽ và dịu êm?",
        birthday: "23/01",
        voucher: "HEAKY#76212026",
        mainImg: "assets/gallery/IMG_20260214_152627.jpg",
        subImgs: ["assets/gallery/IMG_20260525_215201.jpg", "assets/gallery/IMG_20260525_215151.jpg", "assets/gallery/IMG_2195.JPG", "assets/gallery/IMG_8510.JPG"]
    },
    {
        id: 25,
        name: "Nguyễn Võ Tiến Minh",
        title: "Lộn xộn và rối ren",
        fact: "Ai là người luôn lộn xộn và rối ren?",
        birthday: "22/01",
        voucher: "HEAKY#52352026",
        mainImg: "assets/members/Tiến Minh/main image.jpg",
        subImgs: ["assets/members/Tiến Minh/z7810345246406_7ee8dfd5f621cd253af6253f53027f95.jpg"]
    },
    {
        id: 26,
        name: "Hà Minh Khôi",
        title: "Người đàn ông ngại ngùng",
        fact: "Ai là người đàn ông ngại ngùng?",
        birthday: "28/03",
        voucher: "HEAKY#68722026",
        mainImg: "assets/gallery/IMG_1696.JPG",
        subImgs: ["assets/gallery/IMG_2195.JPG", "assets/gallery/IMG_3253.jpeg", "assets/gallery/IMG_9361.JPG", "assets/gallery/IMG_2435.JPG"]
    },
    {
        id: 27,
        name: "Trần Tuấn Khoa",
        title: "Body builder mong manh",
        fact: "Ai là body builder mong manh?",
        birthday: "25/10",
        voucher: "HEAKY#14712026",
        mainImg: "assets/gallery/IMG_20260525_215215.jpg",
        subImgs: ["assets/gallery/IMG_20260214_130847.jpg", "assets/gallery/IMG_8375.JPG", "assets/gallery/IMG_5635.JPG", "assets/gallery/IMG_20260214_131853.jpg"]
    },
    {
        id: 28,
        name: "Chu Nguyễn Gia Huy",
        title: "Mr. Ấm áp",
        fact: "Ai là Mr. Ấm áp - lúc nào cũng rất là ga lăng với các bạn nữ?",
        birthday: "29/09",
        voucher: "HEAKY#64582026",
        mainImg: "assets/gallery/IMG_1691.JPG",
        subImgs: ["assets/gallery/IMG_5635.JPG", "assets/gallery/DSC07049.jpg", "assets/gallery/IMG_20260214_130404.jpg", "assets/gallery/IMG_20260115_151927.jpg"]
    },
    {
        id: 29,
        name: "Đặng Quang Minh",
        title: "Cổ tay vàng",
        fact: "Ai là người có cổ tay vàng?",
        birthday: "10/03",
        voucher: "HEAKY#45002026",
        mainImg: "assets/gallery/IMG_5565.JPG",
        subImgs: ["assets/gallery/IMG_5663.JPG", "assets/gallery/IMG_5453.JPG", "assets/gallery/IMG_6746.JPG", "assets/gallery/IMG_5014.JPG"]
    },
    {
        id: 30,
        name: "Tập thể T1K23",
        title: "Thanh Xuân Rực Rỡ Nhất",
        fact: "Dù có hay cãi nhau, quậy phá và lười biếng, nhưng khi cần đoàn kết thì T1K23 không bao giờ ngán bất kỳ đối thủ nào!",
        birthday: "01/01",
        voucher: "HEAKY#00002026",
        mainImg: "assets/gallery/IMG_2435.JPG",
        subImgs: ["assets/gallery/IMG_20260525_215513.jpg", "assets/gallery/IMG_0757.JPG", "assets/gallery/IMG_0007.JPG", "assets/gallery/IMG_5565.JPG"]
    },
    {
        id: 31,
        name: "Đỗ Minh Khôi",
        title: "Người con trai gương mặt không góc chết",
        fact: "Ai là người con trai có gương mặt không góc chết?",
        birthday: "16/10",
        voucher: "HEAKY#41682026",
        mainImg: "assets/members/Đỗ Khôi/IMG_2234.JPG",
        subImgs: ["assets/members/Đỗ Khôi/IMG_5980.JPG", "assets/members/Đỗ Khôi/IMG_8184.JPG", "assets/members/Đỗ Khôi/IMG_8223.JPG", "assets/members/Đỗ Khôi/IMG_8326.PNG", "assets/members/Đỗ Khôi/IMG_8882.PNG", "assets/members/Đỗ Khôi/IMG_9046.JPG", "assets/members/Đỗ Khôi/IMG_9130.PNG", "assets/members/Đỗ Khôi/IMG_9230.PNG"]
    },
];

const WISHES_DATA = [
    "Chúc thầy luôn dồi dào sức khỏe, giữ mãi ngọn lửa nhiệt huyết và bớt 'đau đầu' với những lứa học trò siêu quậy tiếp theo. Cảm ơn thầy vì đã luôn bao dung cho T1K23!",
    "Chúc Hoàng Long biết cách nói lên ý kiến của mình một cách tinh tế hơn nhen, đậu NV1 và thành công trên chính con đường của mình nhé.",
    "Chúc Minh Khoa đậu NV1, giữ vững tinh thần ham học hỏi, chịu mài mò và thành công trên con đường mình chọn nhé.",
    "Chúc Nhuận Phát biết cách quản lý cảm xúc, biết cân bằng giữa lý trí và trái tim và đậu NV1 nhé.",
    "Chúc Triều đậu NV1, giữ vững phong độ và thành công trên hành trình mới nha.",
    "Chúc Ánh Ngọc đậu NV1, vững bước trên hành trình tương lai, lúc nào cũng vui vẻ và tích cực nhe.",
    "Chúc Quốc Huy đậu NV1, theo đuổi đam mê tới cùng, lúc nào cũng năng lượng và nhiệt huyết nhen.",
    "Chúc Viết Triết biết cách điều chỉnh cảm xúc cá nhân khi cần thiết, giữ vững tinh thần hay giúp đỡ mọi người và thành công trên giấc mơ của mình nhé.",
    "Chúc Huỳnh Duy đậu NV1, tự tin vào bản thân, cởi mở nhiều hơn và hạnh phúc với sự lựa chọn của mình.",
    "Chúc Thuỷ Tiên đậu NV1, giữ vững cá tính và năng lượng của mình, thành công trên con đường mình chọn nhe.",
    "Chúc Trí sẽ hái được \"quả ngọt\" xứng đáng với nỗ lực của mình.",
    "Chúc Khánh Minh luôn tự tin, bản lĩnh và thành công trên mọi con đường phía trước nhé!",
    "Chúc Nga luôn kiên định với con đường mình chọn, đậu NV1 và kĩ lưỡng hơn trong mọi quyết định của mình nhé.",
    "Chúc Bảo Ngọc đậu NV1, luôn giữ được nụ cười hạnh phúc thật sự, và mạnh mẽ trước mọi sóng gió.",
    "Chúc Ngọc Phụng đậu NV1, giữ được sự tích cực và tốt bụng của mình và thành công nhen.",
    "Chúc Phương đậu NV1, luôn mạnh mẽ trước mọi thử thách nha.",
    "Chúc Gia Lộc đậu NV1, trở thành học bá, luôn cười há há.",
    "Chúc Trường Phát lúc nào cũng tự tin vào bản thân mình, (nhưng mà đừng có tự cao nhen), và gặt hái được nhiều thành tựu hơn nữa nhen.",
    "Chúc \"rapper 12T1\" đậu NV1, luôn tràn đầy năng lượng tích cực, vững bước trên con đường của mình.",
    "Chúc Nhã Uyên tự tin vào bản thân, đừng overthinking nữa và thành công trên con đường mình nhé.",
    "Chúc Quốc Thắng đậu NV1 và luôn tràn đầy năng lượng, nhiệt huyết con đường mình chọn nha.",
    "Chúc Diễm Phúc lúc nào cũng tự tin vào bản thân của mình, đậu NV1, tiếp tục theo đuổi đam mê và thành công nhé.",
    "Chúc Trọng Nhân đậu NV1, kiên định với giấc mơ của mình, lúc nào cũng vui vẻ tích cực và gặt hái được nhiều thành công.",
    "Chúc Thanh Ngọc tự tin hơn vào bản thân của mình, tiếp tục theo đuổi đam mê, chinh phục ước mơ và thành công trên con đường mình yêu thích.",
    "Chúc Tiến Minh đậu NV1, sáng suốt hơn trong suy nghĩ và hành động, luôn tin là bản thân sẽ làm được nha.",
    "Chúc Hà Khôi đậu NV1, tự tin hơn và luôn giữ được sự kiên định trên con đường mình chọn nhé.",
    "Chúc Tuấn Khoa đậu NV1, kiên định theo đuổi đam mê riêng của mình và thành công trên con đường mình chọn.",
    "Chúc Chu Huy đậu NV1, luôn giữ được sự nhiệt huyết trong mọi việc. Mong Chu Huy sẽ luôn hết mình mọi lúc.",
    "Chúc Quang Minh lúc nào cũng tự tin vào bản thân, biết cách chia sẻ cảm xúc và vững bước tương lai nhen.",
    "Chúc Thanh Huy đậu NV1, sống đúng với cá tính của mình và thành công trên con đường mình chọn.",
    "Chúc Đỗ Khôi giữ vững được sự tích cực và năng lượng của mình, lúc nào cũng tin tưởng vào bản thân và vững bước trên những con đường sắp tới.",
];

const GALLERY_URLS = [
    "assets/gallery/c65bb644aa67c24e2e0a748f4856b96d.jpeg",
    "assets/gallery/DSC07034.jpg",
    "assets/gallery/DSC07036.jpg",
    "assets/gallery/DSC07037.jpg",
    "assets/gallery/DSC07049.jpg",
    "assets/gallery/DSC07139.jpg",
    "assets/gallery/DSC07319.jpg",
    "assets/gallery/DSC07386.jpg",
    "assets/gallery/DSC07600.jpg",
    "assets/gallery/DSC07601.jpg",
    "assets/gallery/F87A3000.jpeg",
    "assets/gallery/IMG_0007.JPG",
    "assets/gallery/IMG_0011.JPG",
    "assets/gallery/IMG_0497.JPG",
    "assets/gallery/IMG_0499.JPG",
    "assets/gallery/IMG_0539.JPG",
    "assets/gallery/IMG_0558.JPG",
    "assets/gallery/IMG_0572.JPG",
    "assets/gallery/IMG_0574.JPG",
    "assets/gallery/IMG_0747.JPG",
    "assets/gallery/IMG_0752.JPG",
    "assets/gallery/IMG_0757.JPG",
    "assets/gallery/IMG_0765.JPG",
    "assets/gallery/IMG_1184.JPG",
    "assets/gallery/IMG_1193.JPG",
    "assets/gallery/IMG_1280.JPG",
    "assets/gallery/IMG_1283.JPG",
    "assets/gallery/IMG_1287.JPG",
    "assets/gallery/IMG_1366.JPG",
    "assets/gallery/IMG_1377.JPG",
    "assets/gallery/IMG_1676.JPG",
    "assets/gallery/IMG_1684.JPG",
    "assets/gallery/IMG_1691.JPG",
    "assets/gallery/IMG_1696.JPG",
    "assets/gallery/IMG_1700.JPG",
    "assets/gallery/IMG_1718.JPG",
    "assets/gallery/IMG_20250906_133938.jpg",
    "assets/gallery/IMG_20260113_072241.jpg",
    "assets/gallery/IMG_20260115_151706.jpg",
    "assets/gallery/IMG_20260115_151927.jpg",
    "assets/gallery/IMG_20260115_152322.jpg",
    "assets/gallery/IMG_20260214_130146.jpg",
    "assets/gallery/IMG_20260214_130155.jpg",
    "assets/gallery/IMG_20260214_130230.jpg",
    "assets/gallery/IMG_20260214_130404.jpg",
    "assets/gallery/IMG_20260214_130444.jpg",
    "assets/gallery/IMG_20260214_130546.jpg",
    "assets/gallery/IMG_20260214_130601.jpg",
    "assets/gallery/IMG_20260214_130606.jpg",
    "assets/gallery/IMG_20260214_130710.jpg",
    "assets/gallery/IMG_20260214_130819.jpg",
    "assets/gallery/IMG_20260214_130847.jpg",
    "assets/gallery/IMG_20260214_130938.jpg",
    "assets/gallery/IMG_20260214_131009.jpg",
    "assets/gallery/IMG_20260214_131115.jpg",
    "assets/gallery/IMG_20260214_131125.jpg",
    "assets/gallery/IMG_20260214_131134.jpg",
    "assets/gallery/IMG_20260214_131206.jpg",
    "assets/gallery/IMG_20260214_131223.jpg",
    "assets/gallery/IMG_20260214_131721.jpg",
    "assets/gallery/IMG_20260214_131853.jpg",
    "assets/gallery/IMG_20260214_132046.jpg",
    "assets/gallery/IMG_20260214_132053.jpg",
    "assets/gallery/IMG_20260214_132058.jpg",
    "assets/gallery/IMG_20260214_132131.jpg",
    "assets/gallery/IMG_20260214_133154.jpg",
    "assets/gallery/IMG_20260214_141301.jpg",
    "assets/gallery/IMG_20260214_152627.jpg",
    "assets/gallery/IMG_20260525_215013.jpg",
    "assets/gallery/IMG_20260525_215019.jpg",
    "assets/gallery/IMG_20260525_215029.jpg",
    "assets/gallery/IMG_20260525_215036.jpg",
    "assets/gallery/IMG_20260525_215041.jpg",
    "assets/gallery/IMG_20260525_215103.jpg",
    "assets/gallery/IMG_20260525_215111.jpg",
    "assets/gallery/IMG_20260525_215113.jpg",
    "assets/gallery/IMG_20260525_215126.jpg",
    "assets/gallery/IMG_20260525_215151.jpg",
    "assets/gallery/IMG_20260525_215156.jpg",
    "assets/gallery/IMG_20260525_215201.jpg",
    "assets/gallery/IMG_20260525_215215.jpg",
    "assets/gallery/IMG_20260525_215244.jpg",
    "assets/gallery/IMG_20260525_215249.jpg",
    "assets/gallery/IMG_20260525_215257.jpg",
    "assets/gallery/IMG_20260525_215303.jpg",
    "assets/gallery/IMG_20260525_215319.jpg",
    "assets/gallery/IMG_20260525_215326.jpg",
    "assets/gallery/IMG_20260525_215337.jpg",
    "assets/gallery/IMG_20260525_215345.jpg",
    "assets/gallery/IMG_20260525_215356.jpg",
    "assets/gallery/IMG_20260525_215403.jpg",
    "assets/gallery/IMG_20260525_215423.jpg",
    "assets/gallery/IMG_20260525_215433.jpg",
    "assets/gallery/IMG_20260525_215445.jpg",
    "assets/gallery/IMG_20260525_215504.jpg",
    "assets/gallery/IMG_20260525_215513.jpg",
    "assets/gallery/IMG_20260525_215526.jpg",
    "assets/gallery/IMG_20260525_215532.jpg",
    "assets/gallery/IMG_20260525_215541.jpg",
    "assets/gallery/IMG_20260525_215548.jpg",
    "assets/gallery/IMG_2142.JPG",
    "assets/gallery/IMG_2144.JPG",
    "assets/gallery/IMG_2171.JPG",
    "assets/gallery/IMG_2182.JPG",
    "assets/gallery/IMG_2195.JPG",
    "assets/gallery/IMG_2435.JPG",
    "assets/gallery/IMG_2436.JPG",
    "assets/gallery/IMG_2437.JPG",
    "assets/gallery/IMG_2438.JPG",
    "assets/gallery/IMG_2439.JPG",
    "assets/gallery/IMG_2440.JPG",
    "assets/gallery/IMG_2536.JPG",
    "assets/gallery/IMG_2586.JPG",
    "assets/gallery/IMG_2626.JPG",
    "assets/gallery/IMG_3253.jpeg",
    "assets/gallery/IMG_3418.JPG",
    "assets/gallery/IMG_3800.JPG",
    "assets/gallery/IMG_3804.JPG",
    "assets/gallery/IMG_3807.JPG",
    "assets/gallery/IMG_3815.JPG",
    "assets/gallery/IMG_4163.JPG",
    "assets/gallery/IMG_4167.JPG",
    "assets/gallery/IMG_4225.JPG",
    "assets/gallery/IMG_4227.JPG",
    "assets/gallery/IMG_5014.JPG",
    "assets/gallery/IMG_5030.JPG",
    "assets/gallery/IMG_5043.JPG",
    "assets/gallery/IMG_5073.JPG",
    "assets/gallery/IMG_5230.JPG",
    "assets/gallery/IMG_5443.JPG",
    "assets/gallery/IMG_5453.JPG",
    "assets/gallery/IMG_5493.JPG",
    "assets/gallery/IMG_5564.JPG",
    "assets/gallery/IMG_5565.JPG",
    "assets/gallery/IMG_5627.JPG",
    "assets/gallery/IMG_5635.JPG",
    "assets/gallery/IMG_5636.JPG",
    "assets/gallery/IMG_5637.JPG",
    "assets/gallery/IMG_5649.JPG",
    "assets/gallery/IMG_5650.JPG",
    "assets/gallery/IMG_5663.JPG",
    "assets/gallery/IMG_5665.JPG",
    "assets/gallery/IMG_5667.JPG",
    "assets/gallery/IMG_5987.JPG",
    "assets/gallery/IMG_6003.JPG",
    "assets/gallery/IMG_6007.JPG",
    "assets/gallery/IMG_6602.JPG",
    "assets/gallery/IMG_6607.JPG",
    "assets/gallery/IMG_6746.JPG",
    "assets/gallery/IMG_6789.JPG",
    "assets/gallery/IMG_6832.JPG",
    "assets/gallery/IMG_6849.JPG",
    "assets/gallery/IMG_8285.JPG",
    "assets/gallery/IMG_8371.JPG",
    "assets/gallery/IMG_8375.JPG",
    "assets/gallery/IMG_8390.JPG",
    "assets/gallery/IMG_8394.JPG",
    "assets/gallery/IMG_8510.JPG",
    "assets/gallery/IMG_9358.JPG",
    "assets/gallery/IMG_9359.JPG",
    "assets/gallery/IMG_9360.JPG",
    "assets/gallery/IMG_9361.JPG",
    "assets/gallery/IMG_9402.JPG",
    "assets/gallery/IMG_9410.JPG",
    "assets/gallery/IMG_9415.JPG",
    "assets/gallery/IMG_9418.JPG",
    "assets/gallery/IMG_9936.jpeg",
    "assets/gallery/IMG_9954.jpeg",
    "assets/gallery/z7772826838940_2e21a001fd5504e8f24142e0fa18063b.jpg",
    "assets/gallery/z7772881559100_3f060a7ef03fbf2a242ae2a51f5f2731.jpg"
];


const KHOI_WISHES = [
    "Chúc Đỗ Khôi luôn gặp nhiều may mắn, vững vàng và gặt hái thật nhiều thành công trên con đường phía trước",
    "Chào Khôi, Tớ định nói câu này lâu rồi nhưng cứ sợ nói ra sẽ làm mọi thứ trở nên lạ lẫm. Nhưng tớ nghĩ, đã là bạn cùng lớp với nhau thì sự chân thành vẫn là tốt nhất. Không biết từ lúc nào, mỗi lần đến lớp, việc đầu tiên tớ làm là tìm xem Khôi đang ở đâu, làm gì. Tớ thích cách cậu cười, thích cái cách cậu tập trung vào bài học, và thích cả những lúc hai đứa mình trò chuyện với nhau. Tớ nhận ra là tớ không chỉ coi cậu là bạn cùng lớp bình thường nữa, mà tớ thực sự thích Khôi. Tớ không biết cảm xúc của cậu thế nào, nhưng tớ muốn thành thật với chính mình. Cậu có bao giờ nghĩ đến chuyện tụi mình có thể là nhiều hơn bạn không?",
    "Chúc Đỗ sang Mỹ có nhiều bạn, ko cô đơn và nhớ CLA như 1 kỉ niệm đẹp",
    "3 năm cấp 3 không quá dài cũng không quá ngắn, từ những người lạ chúng ta lại là bạn. Ô là người bạn tôi biết từ cấp 2 ( trừ TP vs NP ra) trong đợt đi thi, đâu ngời lại gặp nhau, đồng hành cùng nhau suốt 3 năm cấp 3. Ấn tượng sâu sắc của tôi về ô là \" người j đâu mà đẹp zai lại giàu nx 😆 \" bảo sao không cô nào không mê dc =))), cứ nghĩ lên đại học chắc nhìu chị mê nữa cho mà xem để tôi hóng hớt , đâu có ngờ chúng ta phải tạm chừng chân tại đây 😐. Chúc ô đi đến 1 nơi mới, gặp nhìu bn bè mới và luôn tràn đầy niềm zui như lúc ở đây vs tụi tui vậy đó 👋👋 bái bai và hẹn gặp lại !!! Đỗ Khôi🫡",
    "Mãi iu cô bé bé bỏng của anh",
    "Lên đường bình an Sớm thành tỷ phú Dồi dào sức khỏe Mãi iu T1K23!",
    "From your deskmate, nghe nói Khôi sắp qua mỹ gang gang với tụi mỹ đen và chuẩn bị cho con đường mới của mình. Cả năm qua tui ngồi kế ông cũng có nhiều kỉ niệm đáng nhớ, đôi lúc tui có làm gì có lỗi với ô thì tui xin lỗi nha, có lẽ sẽ không còn gặp lại nữa. Cảm ơn năm vì hành trình vừa qua, tui chúc ông sẽ đạt được nhiều thành công, vững bước trên con đường mới nhé",
    "Hello Đỗ Khôi ạ, từ tận đáy lòng tui luôn. Ba năm qua, tuu với Khôi Đỗ trải qua bao nhiệm kỉ niệm lun í. Mong Đỗ Khôi qua một con đường mới thì vẫn sẽ luôn nhớ tới tụi tui nha. From P with love 💓",
    "Đỗ Khôi qua bên đó tập lo cho cuộc sống mình nhen. Tui tin ô làm được mà. cố lên nhé",
    "chúc Khôi qua bển ăn ngon béo tốt nha",
    "Chúc ông trên chặng đường mới sẽ gặp nhiều may mắn, hoàn thành xuất sắc chặng đường ấy, có thêm nhiều kỉ niệm với những người bạn mới. Đặc biệt, đừng quên sự hiện diện của tụi tui trong 1000days này nha !!!",
    "Sau này ở bên đó vững tâm nha bạn trẻ, mau hoà nhập với bạn bè mới, môi trường mới nha",
    "Đi xa cũng đừng quên những người 3 năm cùng nói cười với ô nhé",
    "Cuộc sống bên đó chắc cũng kh có dễ dàng gì đâu nên ô cố lên nha",
    "Lâu lâu về Việt Nam thăm tụi này nhé",
    "Bản lĩnh lên nha bạn, chúc ô thành công trên con đường mới!!!",
    "Tụi tui mong là những kỷ niệm rực rỡ này cũng như pháo hoa, thắp sáng bầu trời bên đó mỗi lúc ô bùn nhen",
    "T1K23 mãi nhớ về Đỗ Minh Khôiiii",
    "Qua bển có gì khó khăn quá, gọi về đây nha bạn!!",
    "Chúc Đỗ Khôi luôn mạnh mẽ, kiên cường và thành công trong tương lai. Đừng quên những kỷ niệm tươi đẹp của 3 năm cấp 3 nhé!",
    "Ông qua Mỹ có thể học nhưng nhớ để dành thời gian vui chơi nha. Quan trọng là giữ liên lạc nha!!",
    "Chúc ông sẽ có một cuộc sống ý nghĩa và hạnh phúc ở Mỹ",
    "Mãi iu ông và T1K23!",
    "Ba năm, biết nhiêu nhiêu kỉ niệm, giờ chia xa mỗi người mỗi đường, mà không sao hết, đường ai nấy bước tiếp, vẫn là bạn của nhau mà. Chúc ông đi đâu cũng phải dzui dzẻ, nhiều sức khoẻ nha!!!",
    "Chúc ông bên Mỹ ăn ngon, ngủ ngon, học giỏi, làm việc giỏi và mau giàu nha!!",
    "Mong là Khôi bên đó không được cô đơn nha, với tui nghĩ là không nên có người yêu ở đó đâu, nên là chắc là sẽ không cô đơn đâu ha",
    "Mãi nhớ về Đỗ Minh Khôi của 1000days nha!!",
    "Có gì khó khăn nhớ gọi về cho T1K23 nhen",
    "Đỗ Khôi à, nhớ giữ gìn sức khoẻ nha, ở bên đó nhớ ăn uống đầy đủ, đừng bỏ bữa, đừng thức khuya, lo cho bản thân mình trước nhen",
    "Chúc ông qua bển mọi sự hanh thông, vạn sự như ý nhen",
    "Mãi yêu T1K23",
    "Qua đó chơi vui nha!!",
    "Chúc ông sớm trở về Việt Nam với thành quả tốt đẹp nha",
    "Chúc ông luôn có sức khỏe tốt để theo đuổi ước mơ của mình",
    "Nếu có cơ hội qua bển làm ăn thì nói tui tiếng nhen",
    "Qua Mỹ nhớ báo cho tụi này biết nha",
    "Chúc ông luôn giữ được nụ cười rạng rỡ của mình và sớm đạt được mọi điều mong muốn",
    "Tui sẽ luôn nhớ đến những kỉ niệm đẹp của chúng ta",
    "Qua bển nhớ học hành chăm chỉ rồi kiếm thật nhìu tiền mang về chomá tui nhen",
    "Hãy là chính mình, đừng thay đổi",
    "Chúc ông sống tốt, mạnh khoẻ và luôn là người có ích cho xã hội",
    "Nhớ về tụi này nhé",
    "Chúc ông có những trải nghiệm tuyệt vời và đáng nhớ ở Mỹ",
    "Đừng quên nụ cười và sự chân thành của ông nhé",
    "Tụi này mãi yêu ông",
    "Hãy tạo nên những kỉ niệm tuyệt vời ở Mỹ",
    "Chúc ông đạt được mọi điều ước của mình",
    "Hãy giữ gìn sức khoẻ và luôn hạnh phúc nhé",
    "Đừng bao giờ từ bỏ ước mơ của mình",
    "Tụi này mãi tự hào về ông",
    "Mãi là bạn của nhau",
    "Chúc ông luôn mạnh mẽ và vững tin",
    "Hãy cho thế giới thấy tài năng của ông",
    "Chúc ông có những người bạn tuyệt vời ở Mỹ",
    "Đừng bao giờ quên nguồn cội của mình",
    "Chúc ông luôn là niềm tự hào của gia đình và bạn bè",
    "Hãy sống hết mình và tận hưởng cuộc sống",
    "Tụi này sẽ luôn ủng hộ ông",
    "Chúc ông một cuộc sống viên mãn và hạnh phúc",
    "Hẹn gặp lại ở đỉnh vinh quang",
    "Cố lên chàng trai của chúng ta",
    "Chúc mọi thứ như ý muốn",
    "Đừng bao giờ từ bỏ chính mình",
    "Mãi là chàng trai tốt nhất mà chúng tôi biết",
    "Qua đó hãy sống thật với cảm xúc và bản thân",
    "Đừng quên những người bạn đã luôn ở bên",
    "Chúc ông gặt hái nhiều thành công",
    "Hãy là niềm tự hào của chúng tôi",
    "Tụi này luôn dõi theo và ủng hộ ông",
    "Một tương lai rực rỡ đang chờ ông ở phía trước",
    "Hãy là chính mình và tỏa sáng",
    "Đừng bao giờ đánh mất sự chân thành",
    "Chúc ông mọi điều tốt đẹp nhất",
    "Hãy cho thế giới thấy giá trị của ông",
    "Mãi là chàng trai đáng yêu",
    "Đừng quên những kỉ niệm đẹp của chúng ta",
    "Hãy là người truyền cảm hứng cho người khác",
    "Chúc ông tìm thấy hạnh phúc và thành công",
    "Tụi này sẽ luôn nhớ về ông",
    "Đừng bao giờ ngơi nghỉ trên chiến thắng",
    "Hãy là con người mà ông muốn trở thành",
    "Chúc ông luôn mạnh mẽ và kiên cường",
    "Hãy biến ước mơ thành hiện thực",
    "Tụi này tự hào về ông",
    "Đừng bao giờ đánh mất sự kiên nhẫn",
    "Hãy là phiên bản tốt nhất của chính mình",
    "Chúc ông một hành trình đầy ý nghĩa",
    "Hãy trân trọng từng khoảnh khắc",
    "Mãi là bạn tốt của nhau",
    "Chúc ông vượt qua mọi thử thách",
    "Hãy để lại dấu ấn của riêng mình",
    "Đừng bao giờ từ bỏ hy vọng",
    "Tụi này luôn bên ông",
    "Chúc ông một tương lai rạng rỡ",
    "Hãy là chính mình và tỏa sáng",
    "Đừng bao giờ đánh mất sự chân thành",
    "Chúc ông mọi điều tốt đẹp nhất",
    "Hãy cho thế giới thấy giá trị của ông",
    "Mãi là chàng trai đáng yêu",
    "Đừng quên những kỉ niệm đẹp của chúng ta",
    "Hãy là người truyền cảm hứng cho người khác",
    "Chúc ông tìm thấy hạnh phúc và thành công",
    "Tụi này sẽ luôn nhớ về ông",
    "Đừng bao giờ ngơi nghỉ trên chiến thắng",
    "Hãy là con người mà ông muốn trở thành",
    "Chúc ông luôn mạnh mẽ và kiên cường",
    "Hãy biến ước mơ thành hiện thực",
    "Tụi này tự hào về ông",
    "Đừng bao giờ đánh mất sự kiên nhẫn",
    "Hãy là phiên bản tốt nhất của chính mình",
    "Chúc ông một hành trình đầy ý nghĩa",
    "Hãy trân trọng từng khoảnh khắc",
    "Mãi là bạn tốt của nhau",
    "Chúc ông vượt qua mọi thử thách",
    "Hãy để lại dấu ấn của riêng mình",
    "Đừng bao giờ từ bỏ hy vọng",
    "Tụi này luôn bên ông",
    "Chúc ông một tương lai rạng rỡ"
];
